model:
  target: models.aim.AiM
  params:
    stage2_config:
      target: models.stage2.config_mamba.MambaConfig
      params:
        vocab_size: 16384
        d_model: 1024
        n_layer: 48
        d_intermediate: 0
        ssm_cfg:
          layer: Mamba2
        num_classes: 1000
        num_img_tokens: 256
        adaln_group: true
        n_groups: 4
    stage1_config:
      target: models.stage1.vq_model.VQModel
      params:
        ckpt_path: ./checkpoints/vq_f16.pt
        embed_dim: 8
        n_embed: 16384
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
data:
  target: util.data.build_dataset
  params:
    data_path: /data/imagenet-1k/
    final_reso: 256
    hflip: true